version: "3"
services:
  app:
    build: 
      context: ./
      dockerfile: ./infra/app/Dockerfile
    ports:
      - "32280:80"
    working_dir: /app
    volumes:
        - "./app/:/app"
    privileged: true
    tty: true
  composer:
    build:
      context: ./
      dockerfile: ./infra/composer/Dockerfile
    volumes:
        - "./app/:/app/"
    working_dir: /app
  db:
      image: mysql:8
      volumes:
          - db-data:/var/lib/mysql
          - ./infra/db/my.cnf:/etc/mysql/conf.d/my.cnf
          - ./infra/db/init.sql:/tmp/init.sql
      ports:
        - "7306:${DB_PORT:-3306}"
      expose:
        - "${DB_PORT:-3306}"
      environment:
          - MYSQL_ROOT_PASSWORD=T9jm?tGN
          - MYSQL_DATABASE=hakoniwa
          - MYSQL_USER=hakoniwa_user
          - MYSQL_PASSWORD=Vp8mD!uS
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD:-password}"]
        retries: 3
        timeout: 5s
volumes:
  db-data: 
    driver: local
