version: "3"
services:
  app:
    build: 
      context: ./
      dockerfile: ./infra/app/Dockerfile
    ports:
      - "23380:80"
    working_dir: /app
    volumes:
        - "./app/:/var/www/html"
    #   - "./app/:/app"
    privileged: true
    tty: true
