version: "3"
services:
  app:
    build: 
      context: ./
      dockerfile: ./infra/app/Dockerfile
    ports:
      - "${APP_PORT:-54380}:80"
    working_dir: /app
    volumes:
      - ./app/:/app
      # - exclude-mount:/app/vendor
    privileged: true
    tty: true
    # environment:
    #   - APP_ENV=local
  composer:
    build:
      context: ./
      dockerfile: ./infra/composer/Dockerfile
    volumes:
      - ./app/:/app/
    working_dir: /app
  db:
    image: mysql:8
    volumes:
        - db-data:/var/lib/mysql
        - ./infra/db/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./infra/db/init.sql:/tmp/init.sql
    ports:
      - "${DB_PORT:-54306}:3306"
    # expose:
    #   - "${DB_PORT:-54306}"
    environment:
        - MYSQL_ROOT_PASSWORD=T9jm?tGN
        - MYSQL_DATABASE=hakoniwa
        - MYSQL_USER=hakoniwa_user
        - MYSQL_PASSWORD=Vp8mD!uS
        - TZ=Asia/Tokyo
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD:-password}"]
      retries: 3
      timeout: 5s
  db-testing:
    image: mysql:8
    volumes:
      - db-testing-data:/var/lib/mysql
      - ./infra/db-testing/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./infra/db-testing/init.sql:/tmp/init.sql
    ports:
      - "${DB_PORT:-54316}:3306"
    # expose:
    #   - "${DB_PORT:-54316}"
    environment:
      - MYSQL_ROOT_PASSWORD=T9jm?tGN
      - MYSQL_DATABASE=hakoniwa
      - MYSQL_USER=hakoniwa_user
      - MYSQL_PASSWORD=Vp8mD!uS
      - TZ=Asia/Tokyo
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD:-password}"]
      retries: 3
      timeout: 5s
  frontend:
    build: 
      context: ./
      dockerfile: ./infra/frontend/Dockerfile
    tty: true
    volumes:
      - ./app/:/app
    ports:
      - "${FRONT_PORT:-54373}:54373"
volumes:
  db-data: 
    driver: local
  db-testing-data:
    driver: local
  exclude-mount:
    driver: local