<?php

namespace App\Services\Hakoniwa\Status;

use App\Services\Hakoniwa\Util\Point;

class DevelopmentPointsConst
{
    public const LANDFILL_AVAILABLE_POINTS = 5000;
    public const EXCAVATION_AVAILABLE_POINTS = 10000;
    public const DEFENCE_BASE_AVAILABLE_POINTS = 50000;
    public const GROUND_LEVELING_AVAILABLE_POINTS = 100000;
    public const INCREMENT_CITY_CAPACITY_1_AVAILABLE_POINTS = 150000;
    public const CONSTRUCT_SEABED_BASE_AVAILABLE_POINTS = 400000;
    public const INCREMENT_CITY_CAPACITY_2_AVAILABLE_POINTS = 700000;
    public const CONSTRUCT_LARGE_FACTORY_AVAILABLE_POINTS = 1200000;
    public const INCREMENT_FARM_CAPACITY_AVAILABLE_POINTS = 1500000;
    public const INCREMENT_MINE_AND_OILFIELD_CAPACITY_AVAILABLE_POINTS = 1800000;
    public const INCREMENT_CITY_CAPACITY_3_AVAILABLE_POINTS = 3000000;
}
