steps:
  - id: 'pull-image-frontend-build-stage'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull ${_IMAGE_FRONTEND_BUILD_STAGE}:latest || exit 0' ]
    waitFor: [ '-' ]
  - id: 'pull-image-app-deploy-stage'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull ${_IMAGE_APP_DEPLOY_STAGE}:latest || exit 0' ]
    waitFor: [ '-' ]
  - id: 'pull-image-composer'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull ${_COMPOSER_IMAGE_NAME} || exit 0' ]
    waitFor: [ '-' ]
  - id: 'pull-image-node'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull ${_NODE_IMAGE_NAME} || exit 0' ]
    waitFor: [ '-' ]

  - id: 'start-cloud-proxy'
    name: 'gcr.io/cloudsql-docker/gce-proxy:1.15'
    args:
      - '/cloud_sql_proxy'
      - '-dir=/cloudsql'
      - '-instances=$_INSTANCE_CONNECTION_NAME'
    volumes:
      - name: cloudsql
        path: /cloudsql
    waitFor: [ '-' ]

#  - id: 'build-image-frontend-build-stage'
#    name: 'gcr.io/cloud-builders/docker'
#    args: [
#      'build',
#      '-f', './infra/cloudbuild/Dockerfile',
#      '--target', 'frontend_build_stage',
#      '--cache-from', '${_IMAGE_FRONTEND_BUILD_STAGE}',
#      '-t', '${_IMAGE_FRONTEND_BUILD_STAGE}',
#      '.'
#    ]
#    waitFor: [ 'pull-image-frontend-build-stage', 'pull-image-node' ]

  - id: 'build-image-app-deploy-stage'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
      '-c',
      'docker build -f ./infra/cloudbuild/Dockerfile --target deploy_stage --build-arg APP_ENV=${_APP_ENV} --build-arg DB_PASSWORD=$${DB_PASSWORD} --build-arg GOOGLE_CLIENT_SECRET=$${GOOGLE_CLIENT_SECRET} --cache-from ${_IMAGE_APP_DEPLOY_STAGE} -t ${_IMAGE_APP_DEPLOY_STAGE} .' # --cache-from ${_IMAGE_FRONTEND_BUILD_STAGE}
    ]
    secretEnv: [ 'DB_PASSWORD', 'GOOGLE_CLIENT_SECRET' ]
    waitFor: [ 'pull-image-app-deploy-stage', 'pull-image-composer' ] # , 'build-image-frontend-build-stage'

#  - id: 'push-image-frontend-build-stage'
#    name: 'gcr.io/cloud-builders/docker'
#    entrypoint: 'bash'
#    args: [ '-c', 'docker push ${_IMAGE_FRONTEND_BUILD_STAGE} || exit 0' ]
#    waitFor: [ 'build-image-frontend-build-stage' ]

  - id: 'push-image-app-deploy-stage'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker push ${_IMAGE_APP_DEPLOY_STAGE} || exit 0' ]
    waitFor: [ 'build-image-app-deploy-stage' ]

  - id: 'migrate'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
      '-c',
      'docker run -v cloudsql:/cloudsql --env DB_SOCKET=${_DB_SOCKET} --env DB_PASSWORD=$${DB_PASSWORD} ${_IMAGE_APP_DEPLOY_STAGE} bash -c "php artisan config:clear && php artisan migrate --env=${_ENV} && php artisan db:seed --env=${_ENV}"'
    ]
    volumes:
      - name: cloudsql
        path: /cloudsql
    secretEnv: [ 'DB_PASSWORD' ]
    waitFor: [ 'push-image-app-deploy-stage' ]

  - id: 'stop-cloud-proxy'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'docker ps -q --filter ancestor="gcr.io/cloudsql-docker/gce-proxy:1.15" | xargs docker stop'
    waitFor: [ 'migrate' ]

  - id: 'deploy-image'
    name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_CLOUD_RUN_INSTANCE_NAME}',
      '--image', '${_IMAGE_APP_DEPLOY_STAGE}',
      '--region', 'asia-northeast1'
    ]
    waitFor: [ 'migrate' ]

images:
  - '${_IMAGE_FRONTEND_BUILD_STAGE}:latest'
  - '${_IMAGE_APP_DEPLOY_STAGE}:latest'
substitutions:
  _NODE_IMAGE_NAME: 'node:18.15.0-bullseye'
  _COMPOSER_IMAGE_NAME: 'composer:2.5.5'
  _IMAGE_FRONTEND_BUILD_STAGE: 'asia-northeast1-docker.pkg.dev/hakoniwa-dev/build-images/develop/cache/frontend_build_stage'
  _IMAGE_APP_DEPLOY_STAGE: 'asia-northeast1-docker.pkg.dev/hakoniwa-dev/build-images/develop/app_deploy_stage'
  _CLOUD_RUN_INSTANCE_NAME: 'hakoniwa-develop'
  _INSTANCE_CONNECTION_NAME: 'hakoniwa-dev:asia-northeast1:hakoniwa-develop'
  _ENV: 'develop'
  _DB_SOCKET: '/cloudsql/hakoniwa-dev:asia-northeast1:hakoniwa-develop'
availableSecrets:
  secretManager:
  - versionName: projects/171731211938/secrets/hakoniwa-develop-db-pass/versions/latest
    env: 'DB_PASSWORD'
  - versionName: projects/171731211938/secrets/hakoniwa-develop-client-secret/versions/latest
    env: 'GOOGLE_CLIENT_SECRET'
timeout:
  1800s